import { client } from '#/apolo-client';
import { ApolloProvider } from '@apollo/client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
			<html lang='en'>
				<body className={inter.className}>
					<div className='bg-red-600 text-center text-lg p-2'>
						Разрешите странице использование микрофона
					</div>
					{children}
				</body>
			</html>
	);
}
